### ISSUE TITLE
能支持下crosswalk吗

### ISSUE THREAD

**Issue by chenjia** [Cheney925/cordova-plugin-tencent-LiteAV#12]
这个插件ios挺好用的，android能支持下crosswalk吗？

W/System.err: java.lang.ClassCastException: org.crosswalk.engine.XWalkCordovaView cannot be cast to android.webkit.WebView
        at com.hoperun.cordova.tencent.CLiteAV.initialize(CLiteAV.java:131)
        at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.crosswalk.engine.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Cheney925** [comment]
@chenjia crosswalk已经没有人维护了，还是建议你换平台吧
