### ISSUE TITLE
无法正常工作

### ISSUE THREAD

**Issue by worldflyingct** [Cheney925/cordova-plugin-tencent-LiteAV#9]
显示如下log.
```
01-23 02:54:19.265 14217 14300 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-23 02:54:19.282 14217 14299 D NativeLoad: load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/base.apk"],nativeLibraryDirectories=[/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libstlport_shared.so"
01-23 02:54:19.283 14217 14299 D NativeLoad: load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/base.apk"],nativeLibraryDirectories=[/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libsaturn.so"
01-23 02:54:19.283 14217 14299 D NativeLoad: load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/base.apk"],nativeLibraryDirectories=[/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libtxffmpeg.so"
01-23 02:54:19.284 14217 14299 D NativeLoad: load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/base.apk"],nativeLibraryDirectories=[/data/app/cn.worldflying.rtmptest-lQVH9P4IdBp-CFf0O7R0Mg==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libliteavsdk.so"
01-23 02:54:19.285 14217 14299 E zygote64: No implementation found for void com.tencent.liteav.basic.log.TXCLog.nativeLogInit() (tried Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit and Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit__)
01-23 02:54:19.286 14217 14299 W System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.log.TXCLog.nativeLogInit() (tried Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit and Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit__)
01-23 02:54:19.286 14217 14299 W System.err: 	at com.tencent.liteav.basic.log.TXCLog.nativeLogInit(Native Method)
01-23 02:54:19.286 14217 14299 W System.err: 	at com.tencent.liteav.basic.log.TXCLog.init(TXCLog.java:31)
01-23 02:54:19.286 14217 14299 W System.err: 	at com.tencent.rtmp.TXVodPlayer.<init>(TXVodPlayer.java:86)
01-23 02:54:19.286 14217 14299 W System.err: 	at com.hoperun.cordova.tencent.CLiteAV.initVodPlayer(CLiteAV.java:148)
01-23 02:54:19.286 14217 14299 W System.err: 	at com.hoperun.cordova.tencent.CLiteAV.initialize(CLiteAV.java:139)
01-23 02:54:19.286 14217 14299 W System.err: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
01-23 02:54:19.286 14217 14299 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
01-23 02:54:19.286 14217 14299 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
01-23 02:54:19.287 14217 14299 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
01-23 02:54:19.287 14217 14299 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
01-23 02:54:19.287 14217 14299 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-23 02:54:19.287 14217 14299 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
01-23 02:54:19.287 14217 14299 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-23 02:54:19.287 14217 14299 W System.err: 	at android.os.Looper.loop(Looper.java:173)
01-23 02:54:19.287 14217 14299 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
01-23 02:54:19.386   562  2101 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0x7f
01-23 02:54:20.354 14217 14300 D CHCP    : Nothing to update
01-23 02:54:21.008   573   648 E ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
01-23 02:54:21.008   573   648 E ANDR-PERF-OPTSHANDLER:  return value 2
01-23 02:54:21.163   539  2585 D audio_hw_primary: out_standby: enter: stream (0xf4e75000) usecase(1: low-latency-playback)
01-23 02:54:21.228   539  2585 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback speaker
```
我的安装方法为cordova plugin add cordova-plugin-tencent-liteav

**Comment by worldflyingct** [comment]
目前发现是so文件没有被导入，暂时自己找到了个临时解决方案
```
<lib-file src="src/android/libs/liteavsdk.jar" />
<resource-file src="src/android/libs/armeabi" target="jniLibs/armeabi"/>
<resource-file src="src/android/libs/armeabi-v7a" target="jniLibs/armeabi-v7a"/>
```
目前感觉不用这种方式，so文件就打包不进去。

**Comment by Cheney925** [comment]
@worldflyingct 如在Windows环境安装可能会出现hook执行失败，可参照 #3

**Comment by worldflyingct** [comment]
@Cheney925 这个问题确定不是hook失败导致，而是新版本的cordova android原始工程格式发生变化导致。我之前写插件就发现过新版本的cordova工程结构发生了变化，需要用resource-file标签将*.so放到jniLibs目录下，编译时so才能包入apk中。而lib-file标签是官方推荐的，您使用的source-file标签修改了target-dir地址后我试过是可以正常使用的，但是依照我个人不成熟的观点，使用官方提供的方法，官方更新工程格式才会考虑到老版本的兼容问题，source-file标签官方不会特意去维护的。

**Comment by Cheney925** [comment]
@worldflyingct 感谢，我会把这个更新进去。另外一个方案是可以使用7.0.0之前的cordova-android版本，这样目录就没问题。

**Comment by chenjia** [comment]
按照 @worldflyingct 所说的操作成功了，但是一开始使用的cordova@8.1.2, cordova-android@7.1.1安装完插件后so一直打包不进去，执行cordova platform rm android后再cordova platform add android 后就可以了，折腾了一整天
